# Cloudflare Workers/Pages configuration for LocalFishing Frontend
# This file configures deployment settings for the React frontend

name = "aqua-manage-fish-system"
compatibility_date = "2025-07-18"

# Optional: If using Hono or custom functions
main = "dist/index.js"  # adjust to your actual entry point
workers_dev = true
usage_model = "bundled"

[build]
command = "npm run build"

[site]
bucket = "./dist"      # Vite output directory
entry-point = "./"     # Path to functions (if using Hono or similar)

[dev]
port = 8787

# Environment variables for all environments
[vars]
VITE_APP_NAME = "LocalFishing Management System"
VITE_APP_VERSION = "1.0.0"
VITE_API_MODE = "workers"
VITE_API_URL = "https://local-fishing-backend.ntwaribrian262.workers.dev"
VITE_NODE_ENV = "production"
VITE_ENVIRONMENT = "production"
VITE_DEBUG = "false"
VITE_LOG_LEVEL = "error"
VITE_ENABLE_ANALYTICS = "true"

# Production environment
[env.production]
name = "aqua-manage-fish-system-prod"

[env.production.vars]
VITE_API_URL = "https://local-fishing-backend.ntwaribrian262.workers.dev"
VITE_NODE_ENV = "production"
VITE_ENVIRONMENT = "production"
VITE_DEBUG = "false"
VITE_LOG_LEVEL = "error"
VITE_ENABLE_ANALYTICS = "true"

# Preview/staging environment
[env.preview]
name = "aqua-manage-fish-system-preview"

[env.preview.vars]
VITE_API_URL = "https://local-fishing-backend.ntwaribrian262.workers.dev"
VITE_NODE_ENV = "production"
VITE_ENVIRONMENT = "preview"
VITE_DEBUG = "false"
VITE_LOG_LEVEL = "warn"
VITE_ENABLE_ANALYTICS = "false"

# Development environment (for testing deployments)
[env.development]
name = "aqua-manage-fish-system-dev"

[env.development.vars]
VITE_API_URL = "http://localhost:8787"
VITE_NODE_ENV = "development"
VITE_ENVIRONMENT = "development"
VITE_DEBUG = "true"
VITE_LOG_LEVEL = "debug"
VITE_ENABLE_ANALYTICS = "false"
