# Cloudflare Pages configuration for Local Fishing Frontend
# Note: For Pages deployment, build configuration is handled in the Cloudflare dashboard
# This file is used for Pages Functions and environment variables only

name = "local-fishing-frontend"
compatibility_date = "2025-07-10"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "dist"

# Environment variables for production
[env.production]
name = "local-fishing-frontend"

[env.production.vars]
VITE_API_BASE_URL = "https://local-fishing-backend.ntwaribrian262.workers.dev"
VITE_ENVIRONMENT = "production"

# Environment variables for development/preview
[env.preview]
name = "local-fishing-frontend-preview"

[env.preview.vars]
VITE_API_BASE_URL = "https://local-fishing-backend.ntwaribrian262.workers.dev"
VITE_ENVIRONMENT = "preview"

# Custom domains (configure these in Cloudflare dashboard)
# [env.production.route]
# pattern = "your-domain.com/*"
# zone_name = "your-domain.com"
